version: '3.3'
services:
  mysql: # 服务名称
    image: mysql:8.0.27 # mysql版本
    container_name: mysql8 # 容器名称
    environment:
      - MYSQL_ROOT_PASSWORD=root # root用户密码
      # - TZ=Asia/Shanghai # 设置容器时区 这里通过下面挂载方式同步的宿主机时区和时间了,这里忽略
    volumes:
      - ./log:/var/log/mysql # 映射日志目录，宿主机:容器
      - ./data:/var/lib/mysql # 映射数据目录，宿主机:容器
      - ./conf.d:/etc/mysql/conf.d # 映射配置目录，宿主机:容器
      - /etc/localtime:/etc/localtime:ro # 让容器的时钟与宿主机时钟同步，避免时间的问题，ro是read only的意思，就是只读。
    ports:
      - 3306:3306 # 指定宿主机端口与容器端口映射关系，宿主机:容器
    restart: always # 容器意外启动自启

